name: "🐞 Bug Report"
description: Report a problem or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide all required details so we can help effectively.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: It should have...
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or paste error logs. Prefer text over images for logs.
      render: shell
      placeholder: Paste logs or describe the visible error.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide information about the system where the bug occurred.
      placeholder: |
        - OS:
        - Browser (if applicable):
        - Version:
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or relevant information.
      placeholder: Anything else we should know?
