name: "📘 Documentation"
description: Suggest improvements or report issues with documentation
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Found a mistake or unclear section in the docs? Let us know!

  - type: textarea
    id: doc-issue
    attributes:
      label: Describe the documentation issue or suggestion
      description: What is unclear, missing, or could be improved?
      placeholder: Explain the issue or suggestion here.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where did you notice the issue? (e.g., README, API docs, code comments)
      placeholder: e.g., README.md, line 42
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Changess
      description: How would you improve the documentation?
      placeholder: Describe how the text can be improved or rewritten.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots here.
