name: "✨ Enhancement"
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for improvement? Please provide details so we can review it!

  - type: textarea
    id: enhancement-description
    attributes:
      label: Describe the enhancement
      description: What would you like to see improved or added?
      placeholder: Describe the new feature or improvement.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this enhancement useful?
      placeholder: Explain your motivation or the problem it solves.
    validations:
      required: true

  - type: textarea
    id: possible-implementation
    attributes:
      label: Possible Implementation
      description: Do you have ideas for how this could be implemented?
      placeholder: If you have a technical suggestion, include it here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots here.
