@echo off
echo Building Librebucket for Windows...

echo Running golte...
 npx golte
if %errorlevel% neq 0 (
    echo Error: golte failed
    exit /b %errorlevel%
)

set "fileName=dist\embed.go"
(
echo package dist
echo.
echo import (
echo     "embed"
echo.
echo     "github.com/HazelnutParadise/sveltigo"
echo )
echo.
echo //go:embed */**
echo var fsys embed.FS
echo.
echo // Sveltigo is the main middleware to register to your router. It generated by the build step.
echo var Sveltigo = sveltigo.New(&fsys)
) > "%cd%\%fileName%"

echo Building Go binary...
 go build -o librebucket.exe
if %errorlevel% neq 0 (
    echo Error: Go build failed
    exit /b %errorlevel%
)

echo Build completed successfully!